test:
  host: localhost
  username: ubuntu
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  database: portfolio_test
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  charset: utf8mb4